FROM node:22.14.0-alpine3.21 AS build

WORKDIR /src/backend

COPY . /src

RUN npm ci --include=dev

RUN npm run build


FROM node:22.14.0-alpine3.21

WORKDIR /app

ENV NODE_ENV=production

COPY --from=build /src/backend/dist /app/backend/dist
COPY --from=build /src/library/dist /app/library/dist

COPY library/package*.json /app/library/
WORKDIR /app/library
RUN npm ci --omit=dev

COPY backend/package*.json /app/backend/
WORKDIR /app/backend
RUN npm ci --omit=dev

CMD ["node", "dist/main.js"]
