import { en } from 'src/texts/languages/en';
import { i18next } from './i18n';

const translate = i18next.t;

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AnyArgsToStringFn = (...args: any[]) => string;

type TextOrTextFn<T> = T extends string
  ? string | AnyArgsToStringFn
  : T extends object
    ? { [K in keyof T]: TextOrTextFn<T[K]> }
    : T;

export const texts = load();

function reload() {
  const newTexts = load() satisfies TextOrTextFn<typeof en>;
  Object.assign(texts, newTexts);
}

i18next.on('languageChanged', () => {
  reload();
});

i18next.on('loaded', () => {
  reload();
});

function load() {
  return {
    common: {
      administration: translate('common.administration'),
      administrator: translate('common.administrator'),
      apiKey: translate('common.apiKey'),
      appName: translate('common.appName'),
      builtIn: translate('common.builtIn'),
      cancel: translate('common.cancel'),
      chat: translate('common.chat'),
      chatUser: translate('common.chatUser'),
      confirm: translate('common.confirm'),
      copied: translate('common.copied'),
      dangerZone: translate('common.dangerZone'),
      dashboard: translate('common.dashboard'),
      userBucketBadge: translate('common.userBucketBadge'),
      disabled: translate('common.disabled'),
      documentation: translate('common.documentation'),
      documentationLabel: translate('common.documentationLabel'),
      dragAndDrop: translate('common.dragAndDrop'),
      dropZone: translate('common.dropZone'),
      dropZoneDrop: translate('common.dropZoneDrop'),
      edit: translate('common.edit'),
      duplicate: translate('common.duplicate'),
      email: translate('common.email'),
      enabled: translate('common.enabled'),
      endpoint: translate('common.endpoint'),
      errorLoading: translate('common.errorLoading'),
      indexName: translate('common.indexName'),
      error: translate('common.error'),
      generate: translate('common.generate'),
      groupName: translate('common.groupName'),
      headers: translate('common.headers'),
      loginButton: translate('common.loginButton'),
      loginFailed: translate('common.loginFailed'),
      loginText: translate('common.loginText'),
      logout: translate('common.logout'),
      clearConversations: translate('common.clearConversations'),
      monthlyTokens: translate('common.monthlyTokens'),
      monthlyUserTokens: translate('common.monthlyUserTokens'),
      name: translate('common.name'),
      description: translate('common.description'),
      no: translate('common.no'),
      page: (page: number, total: number) => translate('common.page', { page, total }),
      password: translate('common.password'),
      passwordConfirm: translate('common.passwordConfirm'),
      passwordsDoNotMatch: translate('common.passwordsDoNotMatch'),
      reloadAndTryAgain: translate('common.reloadAndTryAgain'),
      remove: translate('common.remove'),
      rename: translate('common.rename'),
      required: translate('common.required'),
      reset: translate('common.reset'),
      roles: translate('common.roles'),
      rolesPlaceholder: translate('common.rolesPlaceholder'),
      save: translate('common.save'),
      saved: translate('common.saved'),
      search: translate('common.search'),
      send: translate('common.send'),
      hide: (thingToHide: string) => translate('common.hide', { thingToHide }),
      show: (thingToShow: string) => translate('common.show', { thingToShow }),
      conversations: translate('common.conversations'),
      menu: translate('common.menu'),
      files: translate('common.files'),
      docs: translate('common.docs'),
      docsHeader: translate('common.docsHeader'),
      subtitle: translate('common.subtitle'),
      text: translate('common.text'),
      title: translate('common.title'),
      tryAgain: translate('common.tryAgain'),
      link: translate('common.link'),
      tokens: translate('common.tokens'),
      uploadLimit: (limit: number, extensionName: string) => translate('common.uploadLimit', { limit, extensionName }),
      userGroup: translate('common.userGroup'),
      userGroups: translate('common.userGroups'),
      yes: translate('common.yes'),
      selectOption: translate('common.selectOption'),
      selectOptions: translate('common.selectOptions'),
      addItem: translate('common.addItem'),
      configurableArguments: translate('common.configurableArguments'),
    },
    chat: {
      conversationNotFound: translate('chat.conversationNotFound'),
      noAccessToConversation: translate('chat.noAccessToConversation'),
      errorLoadingMessagesOrConversation: translate('chat.errorLoadingMessagesOrConversation'),
      newChat: translate('chat.newChat'),
      welcomeText: translate('chat.welcomeText'),
      placeholder: (configuration: string) => translate('chat.placeholder', { configuration }),
      rateConversation: translate('chat.rateConversation'),
      rating: {
        incorrect: translate('chat.rating.incorrect'),
        instructions_not_followed: translate('chat.rating.instructions_not_followed'),
        insufficient_style: translate('chat.rating.insufficient_style'),
        lazy: translate('chat.rating.lazy'),
        refused: translate('chat.rating.refused'),
        other: translate('chat.rating.other'),
      },
      updateRating: {
        ratingHint: translate('chat.updateRating.ratingHint'),
        ratingSubmitted: translate('chat.updateRating.ratingSubmitted'),
        thanksForYourValuableFeedback: translate('chat.updateRating.thanksForYourValuableFeedback'),
        changeResponse: translate('chat.updateRating.changeResponse'),
        retry: translate('chat.updateRating.retry'),
        close: translate('chat.updateRating.close'),
        raitingFailed: translate('chat.updateRating.raitingFailed'),
      },
      ratingHint: translate('chat.ratingHint'),
      removeConversationConfirmText: translate('chat.removeConversationConfirmText'),
      removeConversationConfirmTitle: translate('chat.removeConversationConfirmTitle'),
      removeConversationFailed: translate('chat.removeConversationFailed'),
      renameConversationFailed: translate('chat.renameConversationFailed'),
      clearConversationsConfirmText: translate('chat.clearConversationsConfirmText'),
      clearConversationsConfirmTitle: translate('chat.clearConversationsConfirmTitle'),
      clearConversationsPerformText: translate('chat.clearConversationsPerformText'),
      clearConversationsFailed: translate('chat.clearConversationsFailed'),
      sourceAI: translate('chat.sourceAI'),
      sourceHuman: translate('chat.sourceHuman'),
      sources: {
        sources: translate('chat.sources.sources'),
        content: translate('chat.sources.content'),
        metadata: {
          metadata: translate('chat.sources.metadata.metadata'),
          fileName: translate('chat.sources.metadata.fileName'),
          sourceSystem: translate('chat.sources.metadata.sourceSystem'),
          uniquePathOrId: translate('chat.sources.metadata.uniquePathOrId'),
          pages: translate('chat.sources.metadata.pages'),
          link: translate('chat.sources.metadata.link'),
          version: translate('chat.sources.metadata.version'),
          mimeType: translate('chat.sources.metadata.mimeType'),
          fileSize: translate('chat.sources.metadata.fileSize'),
        },
      },
      speechRecognition: {
        browserNotSupported: translate('chat.speechRecognition.browserNotSupported'),
        languages: {
          de: translate('chat.speechRecognition.languages.de'),
          en: translate('chat.speechRecognition.languages.en'),
        },
        microphoneNotAvailable: translate('chat.speechRecognition.microphoneNotAvailable'),
        speechRecognitionFailed: translate('chat.speechRecognition.speechRecognitionFailed'),
        stopMicrophone: translate('chat.speechRecognition.stopMicrophone'),
        useMicrophone: translate('chat.speechRecognition.useMicrophone'),
      },
      thisMonth: translate('chat.thisMonth'),
      thisWeek: translate('chat.thisWeek'),
      today: translate('chat.today'),
      yesterday: translate('chat.yesterday'),
      filterHeadline: translate('chat.filterHeadline'),
      filterApply: translate('chat.filterApply'),
      filterResetAll: translate('chat.filterResetAll'),
      duplicateConversationSuccess: translate('chat.duplicateConversationSuccess'),
      duplicateConversationFailed: translate('chat.duplicateConversationFailed'),
      prompts: {
        library: translate('chat.prompts.library'),
        searchPlaceholder: translate('chat.prompts.searchPlaceholder'),
        newPrompt: translate('chat.prompts.newPrompt'),
        filter: translate('chat.prompts.filter'),
        rating: translate('chat.prompts.rating'),
        minRating: (rating: number) => translate('chat.prompts.minRating', { rating }),
        type: translate('chat.prompts.type'),
        personal: translate('chat.prompts.personal'),
        team: translate('chat.prompts.team'),
        company: translate('chat.prompts.company'),
        favoritesOnly: translate('chat.prompts.favoritesOnly'),
        sorting: translate('chat.prompts.sorting'),
        newestFirst: translate('chat.prompts.newestFirst'),
        bestRating: translate('chat.prompts.bestRating'),
        mostUsed: translate('chat.prompts.mostUsed'),
        categories: {
          all: translate('chat.prompts.categories.all'),
          email: translate('chat.prompts.categories.email'),
          code: translate('chat.prompts.categories.code'),
          meeting: translate('chat.prompts.categories.meeting'),
          marketing: translate('chat.prompts.categories.marketing'),
          analysis: translate('chat.prompts.categories.analysis'),
        },
        details: translate('chat.prompts.details'),
        execute: translate('chat.prompts.execute'),
        usageCount: (count: number) => translate('chat.prompts.usageCount', { count }),
        ratingCount: (count: number) => translate('chat.prompts.ratingCount', { count }),
        author: (author: string) => translate('chat.prompts.author', { author }),
        createdAt: (date: string) => translate('chat.prompts.createdAt', { date }),
        noResults: translate('chat.prompts.noResults'),
        noResultsHint: translate('chat.prompts.noResultsHint'),
        create: {
          title: translate('chat.prompts.create.title'),
          titleLabel: translate('chat.prompts.create.titleLabel'),
          titlePlaceholder: translate('chat.prompts.create.titlePlaceholder'),
          contentLabel: translate('chat.prompts.create.contentLabel'),
          contentPlaceholder: translate('chat.prompts.create.contentPlaceholder'),
          descriptionLabel: translate('chat.prompts.create.descriptionLabel'),
          descriptionPlaceholder: translate('chat.prompts.create.descriptionPlaceholder'),
          categoryLabel: translate('chat.prompts.create.categoryLabel'),
          categoryPlaceholder: translate('chat.prompts.create.categoryPlaceholder'),
          publicLabel: translate('chat.prompts.create.publicLabel'),
          publicDescription: translate('chat.prompts.create.publicDescription'),
          createButton: translate('chat.prompts.create.createButton'),
          titleValidation: translate('chat.prompts.create.titleValidation'),
          contentValidation: translate('chat.prompts.create.contentValidation'),
          successMessage: translate('chat.prompts.create.successMessage'),
          errorMessage: translate('chat.prompts.create.errorMessage'),
        },
        tooltips: {
          createNew: translate('chat.prompts.tooltips.createNew'),
          searchPrompts: translate('chat.prompts.tooltips.searchPrompts'),
          copyPrompt: translate('chat.prompts.tooltips.copyPrompt'),
          currentVersion: translate('chat.prompts.tooltips.currentVersion'),
          usageCount: translate('chat.prompts.tooltips.usageCount'),
          showDetails: translate('chat.prompts.tooltips.showDetails'),
          useInChat: translate('chat.prompts.tooltips.useInChat'),
          editPrompt: translate('chat.prompts.tooltips.editPrompt'),
          clonePrompt: translate('chat.prompts.tooltips.clonePrompt'),
          copyToClipboard: translate('chat.prompts.tooltips.copyToClipboard'),
        },
        buttons: {
          details: translate('chat.prompts.buttons.details'),
          execute: translate('chat.prompts.buttons.execute'),
          clone: translate('chat.prompts.buttons.clone'),
          toClipboard: translate('chat.prompts.buttons.toClipboard'),
          use: translate('chat.prompts.buttons.use'),
          rate: translate('chat.prompts.buttons.rate'),
          cancel: translate('chat.prompts.buttons.cancel'),
          save: translate('chat.prompts.buttons.save'),
          restore: translate('chat.prompts.buttons.restore'),
          rateThisPrompt: translate('chat.prompts.buttons.rateThisPrompt'),
          submitRating: translate('chat.prompts.buttons.submitRating'),
        },
        placeholders: {
          enterContent: translate('chat.prompts.placeholders.enterContent'),
          optionalDescription: translate('chat.prompts.placeholders.optionalDescription'),
          selectCategory: translate('chat.prompts.placeholders.selectCategory'),
          optionalComment: translate('chat.prompts.placeholders.optionalComment'),
        },
        tabs: {
          details: translate('chat.prompts.tabs.details'),
          versions: translate('chat.prompts.tabs.versions'),
          ratings: translate('chat.prompts.tabs.ratings'),
        },
        labels: {
          title: translate('chat.prompts.labels.title'),
          description: translate('chat.prompts.labels.description'),
          category: translate('chat.prompts.labels.category'),
          content: translate('chat.prompts.labels.content'),
          versionHistory: translate('chat.prompts.labels.versionHistory'),
          yourRating: translate('chat.prompts.labels.yourRating'),
          ratingsFromOthers: translate('chat.prompts.labels.ratingsFromOthers'),
        },
        messages: {
          loading: translate('chat.prompts.messages.loading'),
          notFound: translate('chat.prompts.messages.notFound'),
          noVersions: translate('chat.prompts.messages.noVersions'),
          usedTimes: translate('chat.prompts.messages.usedTimes'),
          current: translate('chat.prompts.messages.current'),
          averageRating: (rating: number, count: number) => translate('chat.prompts.messages.averageRating', { rating, count }),
          usageCount: translate('chat.prompts.messages.usageCount'),
          currentVersion: translate('chat.prompts.messages.currentVersion'),
          usageCountTooltip: translate('chat.prompts.messages.usageCountTooltip'),
          currentVersionTooltip: translate('chat.prompts.messages.currentVersionTooltip'),
          enterPromptContent: translate('chat.prompts.messages.enterPromptContent'),
          versionCommentUpdate: translate('chat.prompts.messages.versionCommentUpdate'),
          versionCommentRestore: translate('chat.prompts.messages.versionCommentRestore'),
          describeChanges: translate('chat.prompts.messages.describeChanges'),
          describeRestore: (versionNumber: number) => translate('chat.prompts.messages.describeRestore', { versionNumber }),
          titlePrefix: translate('chat.prompts.messages.titlePrefix'),
          currentBadge: translate('chat.prompts.messages.currentBadge'),
          saveChanges: translate('chat.prompts.messages.saveChanges'),
          cancelEdit: translate('chat.prompts.messages.cancelEdit'),
          addToFavorites: translate('chat.prompts.messages.addToFavorites'),
          removeFromFavorites: translate('chat.prompts.messages.removeFromFavorites'),
          restoreVersion: (version: number) => translate('chat.prompts.messages.restoreVersion', { version }),
          copyToClipboard: translate('chat.prompts.messages.copyToClipboard'),
          useInChat: translate('chat.prompts.messages.useInChat'),
          cloneAndEdit: translate('chat.prompts.messages.cloneAndEdit'),
        },
        toasts: {
          promptUpdated: translate('chat.prompts.toasts.promptUpdated'),
          updateFailed: translate('chat.prompts.toasts.updateFailed'),
          versionRestored: translate('chat.prompts.toasts.versionRestored'),
          restoreFailed: translate('chat.prompts.toasts.restoreFailed'),
          useFailed: translate('chat.prompts.toasts.useFailed'),
          cloneSuccess: translate('chat.prompts.toasts.cloneSuccess'),
          cloneFailed: translate('chat.prompts.toasts.cloneFailed'),
          copiedToClipboard: translate('chat.prompts.toasts.copiedToClipboard'),
          copyFailed: translate('chat.prompts.toasts.copyFailed'),
          ratingSubmitted: translate('chat.prompts.toasts.ratingSubmitted'),
          ratingFailed: translate('chat.prompts.toasts.ratingFailed'),
        },
      },
    },
    admin: {
      taskCategories: {
        title: translate('admin.taskCategories.title'),
        newCategory: translate('admin.taskCategories.newCategory'),
        sampleData: translate('admin.taskCategories.sampleData'),
      },
      promptCategories: {
        title: translate('admin.promptCategories.title'),
        subtitle: translate('admin.promptCategories.subtitle'),
        newCategory: translate('admin.promptCategories.newCategory'),
        nameLabel: translate('admin.promptCategories.nameLabel'),
        namePlaceholder: translate('admin.promptCategories.namePlaceholder'),
        colorLabel: translate('admin.promptCategories.colorLabel'),
        colorPlaceholder: translate('admin.promptCategories.colorPlaceholder'),
        descriptionLabel: translate('admin.promptCategories.descriptionLabel'),
        descriptionPlaceholder: translate('admin.promptCategories.descriptionPlaceholder'),
        sortOrderLabel: translate('admin.promptCategories.sortOrderLabel'),
        sortOrderPlaceholder: translate('admin.promptCategories.sortOrderPlaceholder'),

        tableHeaders: {
          name: translate('admin.promptCategories.tableHeaders.name'),
          description: translate('admin.promptCategories.tableHeaders.description'),
          color: translate('admin.promptCategories.tableHeaders.color'),
          sortOrder: translate('admin.promptCategories.tableHeaders.sortOrder'),
          prompts: translate('admin.promptCategories.tableHeaders.prompts'),
          created: translate('admin.promptCategories.tableHeaders.created'),
          actions: translate('admin.promptCategories.tableHeaders.actions'),
        },

        createModalTitle: translate('admin.promptCategories.createModalTitle'),
        editModalTitle: translate('admin.promptCategories.editModalTitle'),

        cancel: translate('admin.promptCategories.cancel'),
        create: translate('admin.promptCategories.create'),
        update: translate('admin.promptCategories.update'),

        loading: translate('admin.promptCategories.loading'),
        noCategories: translate('admin.promptCategories.noCategories'),

        nameValidation: translate('admin.promptCategories.nameValidation'),

        deleteConfirmation: (name: string) => translate('admin.promptCategories.deleteConfirmation', { name }),

        createSuccess: translate('admin.promptCategories.createSuccess'),
        createError: translate('admin.promptCategories.createError'),
        updateSuccess: translate('admin.promptCategories.updateSuccess'),
        updateError: translate('admin.promptCategories.updateError'),
        deleteSuccess: translate('admin.promptCategories.deleteSuccess'),
        deleteError: translate('admin.promptCategories.deleteError'),

        sidebarTitle: translate('admin.promptCategories.sidebarTitle'),
      },
    },
    versionComment: {
      label: translate('versionComment.label'),
      placeholder: translate('versionComment.placeholder'),
    },
    dashboard: {
      ratings: translate('dashboard.ratings'),
      tokensPerModelChart: translate('dashboard.tokensPerModelChart'),
      tokensTotalChat: translate('dashboard.tokensTotalChat'),
      requests: translate('dashboard.requests'),
      users: translate('dashboard.users'),
      filterInterval: {
        day: translate('dashboard.filterInterval.day'),
        week: translate('dashboard.filterInterval.week'),
        month: translate('dashboard.filterInterval.month'),
        total: translate('dashboard.filterInterval.total'),
      },
    },
    extensions: {
      add: translate('extensions.add'),
      all: translate('extensions.all'),
      configured: translate('extensions.configured'),
      createConfiguration: translate('extensions.createConfiguration'),
      createConfigurationFailed: translate('extensions.createConfigurationFailed'),
      createExtension: translate('extensions.createExtension'),
      createExtensionFailed: translate('extensions.createExtensionFailed'),
      configurationNotSelected: translate('extensions.configurationNotSelected'),
      configurations: translate('extensions.configurations'),
      configurationsEmpty: translate('extensions.configurationsEmpty'),
      duplicateConfigurationFailed: translate('extensions.duplicateConfigurationFailed'),
      executorEndpoint: translate('extensions.executorEndpoint'),
      executorEndpointHints: translate('extensions.executorEndpointHints'),
      executorHeaders: translate('extensions.executorHeaders'),
      headline: translate('extensions.headline'),
      removeConfigurationConfirmText: translate('extensions.removeConfigurationConfirmText'),
      removeConfigurationConfirmTitle: translate('extensions.removeConfigurationConfirmTitle'),
      removeConfigurationFailed: translate('extensions.removeConfigurationFailed'),
      removeExtensionConfirmText: translate('extensions.removeExtensionConfirmText'),
      removeExtensionConfirmTitle: translate('extensions.removeExtensionConfirmTitle'),
      removeExtensionFailed: translate('extensions.removeExtensionFailed'),
      test: translate('extensions.test'),
      testFailed: translate('extensions.testFailed'),
      testSuccess: translate('extensions.testSuccess'),
      testTooltip: translate('extensions.testTooltip'),
      typeModels: translate('extensions.typeModels'),
      typeOther: translate('extensions.typeOther'),
      typeTools: translate('extensions.typeTools'),
      updateConfiguration: translate('extensions.updateConfiguration'),
      updateConfigurationFailed: translate('extensions.updateConfigurationFailed'),
      updateExtension: translate('extensions.updateExtension'),
      updateExtensionFailed: translate('extensions.updateExtensionFailed'),
      rebuildSchemaFailed: translate('extensions.rebuildSchemaFailed'),
      rebuildSchema: translate('extensions.rebuildSchema'),
      schemaChanged: translate('extensions.schemaChanged'),
      userGroupsHints: translate('extensions.userGroupsHints'),
      warningIncompatibleFilesTools: (tool: string, otherTool: string) =>
        translate('extensions.warningIncompatibleFilesTools', { tool, otherTool }),
      warningNoModel: translate('extensions.warningNoModel'),
      warningTooManyModels: translate('extensions.warningTooManyModels'),
    },
    files: {
      bucketNotSelected: translate('files.bucketNotSelected'),
      buckets: translate('files.buckets'),
      bucketsEmpty: translate('files.bucketsEmpty'),
      createBucket: translate('files.createBucket'),
      bucketType: translate('files.bucketType'),
      createBucketFailed: translate('files.createBucketFailed'),
      deleted: translate('files.deleted'),
      deleting: translate('files.deleting'),
      deselectAll: translate('files.deselectAll'),
      fileSizeLimits: translate('files.fileSizeLimits'),
      headline: translate('files.headline'),
      headlineSearchable: translate('files.headlineSearchable'),
      isDefault: translate('files.isDefault'),
      perUserQuota: translate('files.perUserQuota'),
      allowedFileTypes: translate('files.allowedFileTypes'),
      invalidEndpointError: translate('files.invalidEndpointError'),
      removeBucketConfirmText: translate('files.removeBucketConfirmText'),
      removeBucketConfirmTitle: translate('files.removeBucketConfirmTitle'),
      removeBucketFailed: translate('files.removeBucketFailed'),
      removeFileConfirmText: translate('files.removeFileConfirmText'),
      removeFileConfirmTitle: translate('files.removeFileConfirmTitle'),
      removeFileFailed: translate('files.removeFileFailed'),
      selectAll: translate('files.selectAll'),
      testFailed: translate('files.testFailed'),
      testSuccess: translate('files.testSuccess'),
      testTooltip: translate('files.testTooltip'),
      updateBucket: translate('files.updateBucket'),
      updateBucketFailed: translate('files.updateBucketFailed'),
      uploadFailed: translate('files.uploadFailed'),
      uploadImageFailedNotYetSupported: (fileName: string) => translate('files.uploadImageFailedNotYetSupported', { fileName }),
      uploadImageFailedUseThePaperclip: (fileName: string) => translate('files.uploadImageFailedUseThePaperclip', { fileName }),
      uploading: translate('files.uploading'),
      upload: translate('files.upload'),
      wholeFileTooLarge: translate('files.wholeFileTooLarge'),
    },
    login: {
      loginButton: (provider: string) => translate('login.loginButton', { provider }),
      loginHint: translate('login.loginHint'),
      welcome: translate('login.welcome'),
      authError: translate('login.authError'),
      emptyAuthSettings: translate('login.emptyAuthSettings'),
    },
    userGroups: {
      create: translate('userGroups.create'),
      empty: translate('userGroups.empty'),
      removeConfirmText: translate('userGroups.removeConfirmText'),
      removeConfirmTitle: translate('userGroups.removeConfirmTitle'),
      removeUserGroupFailed: translate('userGroups.removeUserGroupFailed'),
      headline: translate('userGroups.headline'),
      update: translate('userGroups.update'),
      updateFailed: translate('userGroups.updateFailed'),
    },
    users: {
      apiKeyHint: translate('users.apiKeyHint'),
      create: translate('users.create'),
      empty: translate('users.empty'),
      removeConfirmText: translate('users.removeConfirmText'),
      removeConfirmTitle: translate('users.removeConfirmTitle'),
      generateAPIKey: translate('users.generateAPIKey'),
      headline: translate('users.headline'),
      update: translate('users.update'),
      updateFailed: translate('users.updateFailed'),
      warningNotAdminWithKey: translate('users.warningNotAdminWithKey'),
    },
    theme: {
      agentName: translate('theme.agentName'),
      agentNameHints: translate('theme.agentNameHints'),
      appName: translate('theme.appName'),
      language: translate('theme.language'),
      languages: {
        de: translate('theme.languages.de'),
        en: translate('theme.languages.en'),
      },
      appNameHints: translate('theme.appNameHints'),
      customCss: translate('theme.customCss'),
      footer: translate('theme.footer'),
      footerHints: translate('theme.footerHints'),
      headline: translate('theme.headline'),
      links: translate('theme.links'),
      logo: translate('theme.logo'),
      avatarLogo: translate('theme.avatarLogo'),
      avatarLogoHint: translate('theme.avatarLogoHint'),
      backgroundLogo: translate('theme.backgroundLogo'),
      backgroundLogoHint: translate('theme.backgroundLogoHint'),
      logoCurrent: translate('theme.logoCurrent'),
      logoHint: translate('theme.logoHint'),
      logoUpdateFailed: translate('theme.logoUpdateFailed'),
      logoDeleteFailed: translate('theme.logoDeleteFailed'),
      primaryColor: translate('theme.primaryColor'),
      primaryContentColor: translate('theme.primaryContentColor'),
      settings: translate('theme.settings'),
      suggestions: translate('theme.suggestions'),
      suggestionsAdd: translate('theme.suggestionsAdd'),
      suggestionsHints: (maxSuggestions: number) => translate('theme.suggestionsHints', { maxSuggestions }),
      linksHints: translate('theme.linksHints'),
      linksAdd: translate('theme.linksAdd'),
      updateFailed: translate('theme.updateFailed'),
      welcomeText: translate('theme.welcomeText'),
      welcomeTextHints: translate('theme.welcomeTextHints'),
    },
  };
}
